### ISSUE TITLE
Error: Command failed: make world

### ISSUE THREAD

**Issue by InstanceOfMichael** [mike-engel/babel-plugin-bucklescript#3]
```
// by either yarn or npm
yarn add babel-plugin-bucklescript bs-platform
```

```
File "/home/user/code/node_modules/bs-platform/jscomp/runtime/js_internal.ml", line 1:
Error: Could not find the .cmi file for interface
       /home/user/code/node_modules/bs-platform/jscomp/runtime/js_internal.mli.
Building js_internal.mli
make[2]: *** [js_internal.cmj] Error 2
Makefile:61: recipe for target 'js_internal.cmj' failed
make[2]: *** Waiting for unfinished jobs....
Building caml_builtin_exceptions.mli
Building block.mli
Building js_int64.ml
make[2]: Leaving directory '/home/user/code/node_modules/bs-platform/jscomp/runtime'
Makefile:531: recipe for target 'libs' failed
make[1]: *** [libs] Error 2
make[1]: Leaving directory '/home/user/code/node_modules/bs-platform/jscomp'
Makefile:563: recipe for target 'world' failed
make: *** [world] Error 2
child_process.js:634
    throw err;
    ^

Error: Command failed: make world
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at non_windows_npm_release (/home/user/code/node_modules/bs-platform/scripts/install.js:98:27)
    at Object.<anonymous> (/home/user/code/node_modules/bs-platform/scripts/install.js:137:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
```

**Comment by InstanceOfMichael** [comment]
Installing ocaml fixed this: https://ocaml.org/docs/install.html
